### ISSUE TITLE
About the data loading.

### ISSUE THREAD

**Issue by ZhPL1** [XweiQ/Benchmark-GraphFairness#1]
Hi Xiaowei,

Thank you for sharing the code and dataset; they have been really helpful.

I have a question regarding line 80 in load_data.py, where you set labels[labels==-1] = 0. For datasets such as pokec_n and pokec_z, the common practice is to leave these negative labels unprocessed. Is there a specific reason for this different setting, or might it be a mistake?

**Comment by XweiQ** [comment]
Good question! As our paper mentioned in Section 4.2 Obs3, the previous work merged multiple labels into binary labels during the processing of real-world datasets. We consider this as an issue in existing real-world datasets, so we keep this setting for the analysis experiments in Section 4. Of course you can leave these negative labels unprocessed, but you need to be careful about the difference from previous works.

**Comment by ZhPL1** [comment]
Thank you for your response. 

I agree with the point made in Obs3. However, I am still a bit confused. In the Pokec_z dataset, for example, after merging, the labels are -1, 0, and 1. Subsequently, only the data with labels 0 and 1 are used for splitting. But when -1 is turned into 0 (as line 80 in load_data.py), it seems that the amount of data used for splitting increases. Could you please clarify this aspect?

**Comment by XweiQ** [comment]
You're right, the code on line 80 `labels[labels == -1] = 0` should be removed. I checked and found that this code is a mistake that comes up when I merged different code files and pushed them to GitHub. We didn't run the experiments with this line.

Thanks for double checking and pointing out this mistake. I'll fix it.

**Comment by ZhPL1** [comment]
Thanks for your efforts :)
